---
kind: pipeline
name: default

steps:
- name: build
  image: docker:dind
  volumes:
  - name: dockersock
    path: /var/run
  commands:
  - sleep 5 # give docker enough time to start
  - docker build -t patrickstigler/py-stocks-api:latest .
  - docker push patrickstigler/obs-ndi:latest
  
 - name: publish
  image: docker:dind
  volumes:
  - name: dockersock
    path: /var/run
  commands:
  - sleep 5 # give docker enough time to start
  - docker push patrickstigler/obs-ndi:latest