#Drone CI File!

kind: pipeline
type: docker
name: default

steps:
- name: build
    image: docker:latest
    volumes:
      - name: docker_sock
        path: /var/run/docker.sock
  commands:
    - docker build . --no-cache -t patrickstigler/py-stock-api:latest

- name: publish  
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: patrickstigler/py-stocks-api
    auto_tag: true