kind: pipeline
name: default

steps:
- name: docker  
  image: plugins/docker
  settings:
    repo: patrickstigler/py-stocks-api
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    tags: latest