#Drone CI File!

kind: pipeline
type: docker
name: default

steps:
- name: build
    image: docker:latest
    settings:
        username: docker_username
        password: docker_password
        tags: latest
    volumes:
      - name: docker_sock
        path: /var/run/docker.sock
  commands:
    - docker build . --no-cache -t patrickstigler/py-stock-api:latest